Api:
  Port: 8082
  AllowOrigins:
    - '*'
  AllowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  AllowHeaders:
    - Content-Type
  Production: false
  Admin: true
Consumer:
  Port: 8081
Postgres:
  Host: localhost
  Port: 5432
  User: degen-date-user
  Name: degen-date-db
