Api:
  Port: 8080
  AllowOrigins:
    - '*'
  AllowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  AllowHeaders:
    - Content-Type
  Production: false
  Admin: true
Postgres:
  Host: degen-date-postgres-1
  Port: 5432
  User: degen-date-user
  Name: degen-date-db
